# Generated by Django 4.2.19 on 2025-04-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voltage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='loadflow.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impedance', models.FloatField()),
                ('from_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_lines', to='loadflow.bus')),
                ('to_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_lines', to='loadflow.bus')),
            ],
        ),
    ]
