# Generated by Django 4.2.19 on 2025-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='impedance',
            new_name='impedance_imag',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='power',
            new_name='load_imag',
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('SLACK', 'Slack'), ('PV', 'PV'), ('PQ', 'PQ')], default='PQ', max_length=10),
        ),
        migrations.AddField(
            model_name='line',
            name='impedance_real',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='load_real',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='voltage',
            field=models.FloatField(default=1.0),
        ),
    ]
